language: android

jdk: oraclejdk8

install:
  - echo y | android update sdk -u -a -t tools
  - echo y | android update sdk -u -a -t platform-tools
  - echo y | android update sdk -u -a -t android-28
  - echo y | android update sdk -u -a -t extra-google-m2repository
  - echo y | android update sdk -u -a -t extra-android-m2repository

script: ./gradlew clean assembleDebug --scan -s

branches:
  except:
    - gh-pages

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
